# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'visual.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1280, 720)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.channelListWidget = QtWidgets.QListWidget(self.centralwidget)
        self.channelListWidget.setGeometry(QtCore.QRect(1020, 10, 256, 301))
        self.channelListWidget.setObjectName("channelListWidget")
        self.currencyListWidget = QtWidgets.QListWidget(self.centralwidget)
        self.currencyListWidget.setGeometry(QtCore.QRect(1020, 320, 256, 261))
        self.currencyListWidget.setObjectName("currencyListWidget")
        self.startQueryButton = QtWidgets.QPushButton(self.centralwidget)
        self.startQueryButton.setGeometry(QtCore.QRect(1020, 650, 251, 23))
        self.startQueryButton.setObjectName("startQueryButton")
        self.startDateTimeEditor = QtWidgets.QDateTimeEdit(self.centralwidget)
        self.startDateTimeEditor.setGeometry(QtCore.QRect(1020, 590, 194, 24))
        self.startDateTimeEditor.setObjectName("startDateTimeEditor")
        self.endDateTimeEditor = QtWidgets.QDateTimeEdit(self.centralwidget)
        self.endDateTimeEditor.setGeometry(QtCore.QRect(1020, 620, 194, 24))
        self.endDateTimeEditor.setObjectName("endDateTimeEditor")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 1021, 681))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.plotWidget = MplWidget(self.tab)
        self.plotWidget.setGeometry(QtCore.QRect(10, 10, 1001, 641))
        self.plotWidget.setObjectName("plotWidget")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.plotWidget_2 = MplWidget(self.tab_2)
        self.plotWidget_2.setGeometry(QtCore.QRect(10, 10, 1001, 641))
        self.plotWidget_2.setObjectName("plotWidget_2")
        self.tabWidget.addTab(self.tab_2, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1280, 20))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "visualize Superchat times"))
        self.startQueryButton.setText(_translate("MainWindow", "query database/draw"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Tab 1"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Tab 2"))
from mplwidget import MplWidget


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
